name: Build and Package JAR (Maven)

on:
  workflow_call:
    inputs:
      jdk-version:
        required: false
        type: string
        default: '21'
      artifact-name:
        required: false
        type: string
        default: 'plugin-jar'
      pom-path:
        required: false
        type: string
        default: 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.jdk-version }}
          distribution: 'temurin'
          cache: maven

      - name: Build JAR with Maven
        run: mvn -B package --file ${{ inputs.pom-path }} -DskipTests

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: target/*.jar
          if-no-files-found: error
